BaseUrl= "http://jlopezsi.github.io"
LanguageCode= "es-ES"
Title= "Consumption, markets, and culture"
paginate = 5
DisqusShortname = "jlopezsi"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "I'm a researcher at UAB"
  cover = "images/cover.jpg"
  author = "Jordi L. Sintas"
  authorlocation = "Barcelona, Spain"
  authorwebsite = "http://jlopezsi.github.io"
  bio= "Researcher at UAB"
  logo = "images/jlopezsi.png"
  #∫googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "" 
  githubName = "jlopezsi"
  twitterName = "jlopezsi"
  facebookName = "jlopezsi"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
  
  [[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"



  

