---
contentdir: "content"
layoutdir: "layouts"
publishdir: ""
indexes:
  category: "categories"
  page: "pages"
  cv: “cvs”
baseurl: "http://jlopezsi.github.io/“
title: “Jordi’s Blog Template for GitHub Pages"
...
