---
contentdir: "content"
layoutdir: "layouts"
publishdir: ""
indexes:
  category: "categories"
  page: "pages"
baseurl: "http://jlopezsi.github.io/“
title: “Jordi’s Blog Template for GitHub Pages"
permalinks: 
  post: ":year/:month/:day/:title/"
  fixed: ":title/"
---
