---
contentdir: "content"
layoutdir: "layouts"
publishdir: ""
indexes:
  category: "categories"
  page: "pages"
  vita: “vitas”
baseurl: "http://jlopezsi.github.io/“
title: “Jordi’s Blog Template for GitHub Pages"
name:  “Jordi López“
email: “jordi.lopez@uab.es”
twiter: “jlopezsi”
...
